In [4]:
import numpy as np

In [5]:
np.arange(5,10,0.5)

array([ 5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5])

###Array Concatenation and splitting
Aixs :
y->0 - vertical  
x->1 - horizontal
by default->0

concatenate()
stacking vertically and horizontally:
vstack() : no of cols should be same for both arrays
hstack() : no of rows should be same for both arrays

splitting arrays:
split(x,[position of array])
vsplit(xx,[position of array]) : splits vertically
hsplit(xx,[position of array]) : splits horizontally

Computation on Numpy Arrays (operates universal)
+
*
/
multiply(array,value)

%timeit
python sum
Numpy sum -> np.sum
absolute(array)
sin(arrray)
problems
1)500 -1000 size 20*30
2)split above matrix with all function

In [6]:
data = np.random.randint(1,10,size=5)

In [7]:
data

array([4, 3, 2, 9, 4])

In [8]:
np.concatenate([data,data])

array([4, 3, 2, 9, 4, 4, 3, 2, 9, 4])

ValueError: high is out of bounds for int32

array([6, 1, 9, 4, 1, 9, 3, 6, 9, 8, 0, 2, 3, 4, 6, 5, 1, 4, 9, 1, 2, 2, 1,
       5, 2, 8, 2, 3, 9, 5, 5, 8, 2, 8, 7, 9, 3, 8, 6, 4, 3, 6, 5, 3, 2, 6,
       8, 2, 7, 3, 8, 1, 8, 1, 6, 2, 9, 8, 1, 3, 3, 4, 9, 0, 1, 2, 1, 0, 6,
       9, 4, 0, 8, 8, 9, 0, 7, 1, 2, 5, 9, 3, 8, 1, 0, 9, 0, 1, 4, 4, 3, 2,
       3, 3, 5, 6, 2, 3, 2, 4])