*Aggregations
Pandas uses Numpy for aggregations e.g min, max, mean etc
np.max, np.sum, np.min for multidimentional arrays
np.argmax() : gives index of max valued element
np.argmin() : gives index of min value
np.mean()
np.median()
np.std()
np.all()  :returns True if all elements are non zero
np.any()  :returns True if any of the element is non-zero

*Comparisons, Masks and Boolean Logic
x=np.array([1,2,3,4,5,6])
x[x<2]
x < 2 is an mask array
&,| ==,

In [3]:
import numpy as np

In [6]:
L = np.random.random(100)

In [8]:
%timeit L.sum()

The slowest run took 6.16 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 6.79 µs per loop


In [10]:
%timeit np.sum(L)

The slowest run took 5.18 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 10.9 µs per loop


In [12]:
np.sum(L)

53.043817715009872

In [14]:
L.sum()

53.043817715009872

In [20]:
data = np.arange(100)

In [27]:
##Print all multiples of 2 and 3 from 0 to 100 numbers
data[((data%2) == 0) & ((data%3)==0)]

array([ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 84, 90, 96])

In [29]:
L.max()

0.9955270041077604

In [31]:
np.max(L)

0.9955270041077604

In [33]:
L.min()

0.016496548969139768

In [35]:
np.min(L)

0.016496548969139768

In [39]:
np.mean(L)

0.53043817715009878

In [41]:
np.median(L)

0.52379759730600406

In [44]:
np.std(L)

0.29061049404635447

# Multidimentional Aggregations

In [47]:
np.random.random((3,3))

array([[ 0.60967269,  0.51331245,  0.26417851],
       [ 0.03082306,  0.93163212,  0.11127399],
       [ 0.73974646,  0.07202868,  0.10418973]])

In [50]:
np.random.randint(1,100,(3,3))

array([[28, 22, 93],
       [84, 12, 45],
       [14, 56, 31]])

In [52]:
np.arange(1,5,2)

array([1, 3])

In [63]:
M = np.random.randint(1,10,(3,4))

In [64]:
M

array([[5, 9, 3, 9],
       [6, 3, 1, 7],
       [3, 5, 4, 2]])

In [65]:
np.sum(M)

57

In [67]:
np.sum(M,axis=0)

array([14, 17,  8, 18])

In [69]:
np.sum(M, axis=1)

array([26, 17, 14])

In [71]:
np.mean(M)

4.75

In [73]:
np.median(M)

4.5

In [75]:
np.std(M)

2.4874685927665499

In [77]:
np.mean(M,axis=1)

array([ 6.5 ,  4.25,  3.5 ])

In [79]:
np.mean(M,axis=0)

array([ 4.66666667,  5.66666667,  2.66666667,  6.        ])

In [91]:
#Argmax()
l = np.random.randint(1,100,size=10)

In [92]:
l

array([63, 91, 31, 68, 41, 56,  9, 14, 60,  5])

In [94]:
np.argmax(l)

1

In [96]:
np.argmin(l)

9

In [105]:
l = np.random.randint(1,100,(3,3))

In [106]:
l

array([[29, 43, 73],
       [83, 80, 17],
       [41, 24, 70]])

In [108]:
np.argmax(l,axis=1)

array([2, 0, 2], dtype=int64)

In [110]:
np.argmax(l,axis=0)

array([1, 1, 0], dtype=int64)

In [112]:
np.argmin(l, axis=0)

array([0, 2, 1], dtype=int64)

In [114]:
np.argmin(l, axis=1)

array([0, 2, 1], dtype=int64)

In [117]:
d = np.arange(10)

In [119]:
np.any(d)

True

In [121]:
np.all(d)

False

# Comparison, Masks and Boolean

In [127]:
x = np.arange(10)

In [129]:
#boolean masks
x < 5

array([ True,  True,  True,  True,  True, False, False, False, False, False], dtype=bool)

In [131]:
x[x<5]

array([0, 1, 2, 3, 4])

In [133]:
x[(x < 5) | (x > 8)]

array([0, 1, 2, 3, 4, 9])

In [137]:
x[(x < 10 ) & (x > -1)]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [139]:
45 or 5

45

In [141]:
8 or 10

8

In [143]:
8 and 10

10

In [146]:
bin(8)

'0b1000'

In [148]:
bin(10)

'0b1010'

In [154]:
bin(8) and bin(10)

'0b1010'

In [163]:
l = np.random.randint(1,100,10)

In [164]:
l

array([25, 96, 76, 63, 23, 92, 90, 60,  2, 79])

In [165]:
indx = [3,4,5]

In [167]:
l[indx]

array([63, 23, 92])

In [169]:
M

array([[5, 9, 3, 9],
       [6, 3, 1, 7],
       [3, 5, 4, 2]])

In [178]:
indx = np.array([1])

In [180]:
M[indx]

array([[6, 3, 1, 7]])

In [182]:
indx=np.array([1,2])

In [184]:
M[indx]

array([[6, 3, 1, 7],
       [3, 5, 4, 2]])

In [187]:
indx = np.array([[1],[2]])

In [189]:
M[indx]

array([[[6, 3, 1, 7]],

       [[3, 5, 4, 2]]])

In [198]:
M = np.random.randint(1,100,(5,5))
M

array([[81, 81, 54, 58, 91],
       [10, 29, 36,  2, 10],
       [82, 68, 49,  2, 40],
       [68, 34,  4, 77, 72],
       [ 5, 30, 81, 14, 37]])

In [201]:
np.arange(1,5,2)

array([1, 3])

In [203]:

M[np.arange(1,5,2)]
#Generate indices programmatically

array([[10, 29, 36,  2, 10],
       [68, 34,  4, 77, 72]])

In [210]:
l = np.arange(10,dtype=int)
l

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [212]:
np.shape(l)

(10L,)

In [214]:
# Adds one more dimension
l[:, np.newaxis].shape

(10L, 1L)

In [217]:
l[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [221]:
m = np.arange(12).reshape((3,4))

In [222]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [228]:
mn = m[:,np.newaxis]
mn

array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]]])

In [230]:
np.shape(mn)

(3L, 1L, 4L)

In [232]:
M

array([[81, 81, 54, 58, 91],
       [10, 29, 36,  2, 10],
       [82, 68, 49,  2, 40],
       [68, 34,  4, 77, 72],
       [ 5, 30, 81, 14, 37]])

In [234]:
M.transpose()

array([[81, 10, 82, 68,  5],
       [81, 29, 68, 34, 30],
       [54, 36, 49,  4, 81],
       [58,  2,  2, 77, 14],
       [91, 10, 40, 72, 37]])

In [236]:
M.T

array([[81, 10, 82, 68,  5],
       [81, 29, 68, 34, 30],
       [54, 36, 49,  4, 81],
       [58,  2,  2, 77, 14],
       [91, 10, 40, 72, 37]])

In [238]:
a = (1)
type(a)

int

In [240]:
a = (1,)
type(a)

tuple

# Sort and Argsort

In [259]:
np.sort([1,3,5,9,78,85,2,3])

array([ 1,  2,  3,  3,  5,  9, 78, 85])

In [262]:
np.argsort([8,2,5,4])

array([1, 3, 2, 0], dtype=int64)

In [263]:
M

array([[81, 81, 54, 58, 91],
       [10, 29, 36,  2, 10],
       [82, 68, 49,  2, 40],
       [68, 34,  4, 77, 72],
       [ 5, 30, 81, 14, 37]])

In [265]:
np.sort(M,axis=0)

array([[ 5, 29,  4,  2, 10],
       [10, 30, 36,  2, 37],
       [68, 34, 49, 14, 40],
       [81, 68, 54, 58, 72],
       [82, 81, 81, 77, 91]])

In [267]:
np.sort(M,axis=1)


array([[54, 58, 81, 81, 91],
       [ 2, 10, 10, 29, 36],
       [ 2, 40, 49, 68, 82],
       [ 4, 34, 68, 72, 77],
       [ 5, 14, 30, 37, 81]])

In [268]:
#Practice 

In [272]:
d = np.arange(5)

In [274]:
d * 2

array([0, 2, 4, 6, 8])

In [276]:
2 * d

array([0, 2, 4, 6, 8])

In [278]:
d **2 

array([ 0,  1,  4,  9, 16])

In [280]:
2**d

array([ 1,  2,  4,  8, 16])

1